[[language]]
name = "haskell"
auto-format = true

[language-server.haskell-language-server.config]
formattingProvider = "fourmolu"
plugin.fourmolu.config.external = true

[[language]]
name = "rust"
auto-format = true

[language-server.ucm]
command = "nc"
args = ["localhost", "5757"]

[[language]]
name = "unison"
scope = "source.unison"
injection-regex = "unison"
file-types = ["u"]
shebangs = []
roots = []
auto-format = false
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "ucm" ]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml", "yml", "yaml.enc", "yml.enc"]
