format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$haskell\
$nix_shell\
$cmd_duration\
$line_break\
$character\
"""

[nix_shell]
format = "$symbol"
heuristic = true
